
services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./kong-db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  kong-bootstrap:
    image: kong:3.4
    container_name: kong-bootstrap
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap
    restart: "no"  # จะรันครั้งเดียวแล้วหยุด

  kong-gateway:
    image: kong:3.4
    container_name: kong-gateway
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"   # Public API (Proxy)
      - "8001:8001"   # Admin API
    restart: always

  konga-ui:
    image: pantsel/konga:latest
    container_name: konga-ui
    networks:
      - kong-net
    depends_on:
      - kong-gateway
      - kong-database
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
    restart: always

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      - kong-gateway
    ports:
      - "3001:3001"
    networks:
      - kong-net

  product-service:
    build: ./product-service
    container_name: product-service
    restart: always
    depends_on:
      - kong-gateway
    ports:
      - "4001:4001"
    networks:
      - kong-net
      
volumes:
  kong-db-data:

networks:
  kong-net:
    driver: bridge