
services:
  kong-gateway:
    image: kong:3.4
    container_name: kong-gateway
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_LOG_LEVEL: debug
    volumes:
      - ./kong-gateway/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"   # Public API (proxy)
      - "8001:8001"   # Admin API

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      - kong-gateway
    ports:
      - "3001:3001"
    networks:
      - kong-net

  product-service:
    build: ./product-service
    container_name: product-service
    restart: always
    depends_on:
      - kong-gateway
    ports:
      - "4001:4001"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge